# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GreenFarm-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'OpenCV', '3.1.0.1'
   
end
