delete from gf_rent;
delete from gf_land;
delete from gf_farm;
delete from gf_user;
delete from gf_plant_task ;
delete from gf_task_detail;
delete from gf_task_step;
delete from gf_step_template;
delete from gf_seed;
delete from gf_carbon_credit_daily;
delete from gf_community_member;
delete from gf_community;